#!/bin/csh
#/usr/local/bin/wp cli update --allow-root --yes
sudo -u nobody -g nobody -- /usr/local/bin/wp --path=/usr/local/www/ostreff.info/ core update
sudo -u nobody -g nobody -- /usr/local/bin/wp --path=/usr/local/www/albena-bg.be/ core update
sudo -u nobody -g nobody -- /usr/local/bin/wp --path=/usr/local/www/wordpress/ core update
sudo -u nobody -g nobody -- /usr/local/bin/wp --path=/home/classic-bg.net/new-site/ core update
sudo -u nobody -g nobody -- /usr/local/bin/wp --path=/home/classic-bg.net/tmp-site/ core update
sudo -u nobody -g nobody -- /usr/local/bin/wp --path=/home/realesr/ core update
sudo -u nobody -g nobody -- /usr/local/bin/wp --path=/usr/local/www/ostreff.info/ plugin update --all
sudo -u nobody -g nobody -- /usr/local/bin/wp --path=/usr/local/www/albena-bg.be/ plugin update --all
sudo -u nobody -g nobody -- /usr/local/bin/wp --path=/usr/local/www/wordpress/ plugin update --all
sudo -u nobody -g nobody -- /usr/local/bin/wp --path=/home/classic-bg.net/new-site/ plugin update --all
sudo -u nobody -g nobody -- /usr/local/bin/wp --path=/home/classic-bg.net/tmp-site/ plugin update --all
sudo -u nobody -g nobody -- /usr/local/bin/wp --path=/home/realesr/ plugin update --all
sudo -u nobody -g nobody -- /usr/local/bin/wp --path=/usr/local/www/ostreff.info/ theme update --all
sudo -u nobody -g nobody -- /usr/local/bin/wp --path=/usr/local/www/albena-bg.be/ theme update --all
sudo -u nobody -g nobody -- /usr/local/bin/wp --path=/usr/local/www/wordpress/ theme update --all
sudo -u nobody -g nobody -- /usr/local/bin/wp --path=/home/classic-bg.net/new-site/ theme update --all
sudo -u nobody -g nobody -- /usr/local/bin/wp --path=/home/classic-bg.net/tmp-site/ theme update --all
sudo -u nobody -g nobody -- /usr/local/bin/wp --path=/home/realesr/ theme update --all
sudo -u nobody -g nobody -- /usr/local/bin/wp --path=/home/realesr/ language core update
sudo -u nobody -g nobody -- /usr/local/bin/wp --path=/home/realesr/ language plugin update --all
sudo -u nobody -g nobody -- /usr/local/bin/wp --path=/home/realesr/ language theme update --all
sudo -u nobody -g nobody -- /usr/local/bin/wp --path=/home/classic-bg.net/tmp-site/ language core update
sudo -u nobody -g nobody -- /usr/local/bin/wp --path=/home/classic-bg.net/tmp-site/ language plugin update --all
sudo -u nobody -g nobody -- /usr/local/bin/wp --path=/home/classic-bg.net/tmp-site/ language theme update --all
sudo -u nobody -g nobody -- /usr/local/bin/wp --path=/home/classic-bg.net/new-site/ language core update
sudo -u nobody -g nobody -- /usr/local/bin/wp --path=/home/classic-bg.net/new-site/ language plugin update --all
sudo -u nobody -g nobody -- /usr/local/bin/wp --path=/home/classic-bg.net/new-site/ language theme update --all
sudo -u nobody -g nobody -- /usr/local/bin/wp --path=/usr/local/www/wordpress/ language core update
sudo -u nobody -g nobody -- /usr/local/bin/wp --path=/usr/local/www/wordpress/ language plugin update --all
sudo -u nobody -g nobody -- /usr/local/bin/wp --path=/usr/local/www/wordpress/ language theme update --all
sudo -u nobody -g nobody -- /usr/local/bin/wp --path=/usr/local/www/ostreff.info/ language core update
sudo -u nobody -g nobody -- /usr/local/bin/wp --path=/usr/local/www/ostreff.info/ language plugin update --all
sudo -u nobody -g nobody -- /usr/local/bin/wp --path=/usr/local/www/ostreff.info/ language plugin theme --all
sudo -u nobody -g nobody -- /usr/local/bin/wp --path=/usr/local/www/albena-bg.be/ language core update
sudo -u nobody -g nobody -- /usr/local/bin/wp --path=/usr/local/www/albena-bg.be/ language plugin update --all
sudo -u nobody -g nobody -- /usr/local/bin/wp --path=/usr/local/www/albena-bg.be/ language plugin theme --all
